import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@mui/joy";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen overflow-hidden">
          <div className="flex justify-center h-24 bg-indigo-500">
              <div className="self-center text-white font-mono text-3xl ">
                Welcome To Galaxy Pulse
              </div>
          </div>
          <div className="overflow-scroll h-full w-full ">{children}</div>
        </div>
      </body>
    </html>
  );
}
